version: '3.4'

services:
  apiprod:
    image: api-produtos
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env
    ports:
      #- 3000:3000
      - "${PORT}:${PORT}"
